### ISSUE TITLE
add discussionId in the ReportDiscussionCommentDetails Schema

### ISSUE THREAD

**Issue by Dishebh** [CodeTrophs/Backend#125]
### Current Scenario

The `ReportDiscussionComment` holds and stores only `reason`, `userId` and `discussionCommentId` in its schema.

### Enhancement

Add `discussionId` in the same schema and you can extract it from the path `POST /:discussionId/comment/:commentId` as a route parameter.

**Comment by ankitvashisht12** [comment]
I would like to work on this issue

**Comment by Dishebh** [comment]
Sure, go ahead.
