### ISSUE TITLE
restrict a user to report a particular discussion only one time 

### ISSUE THREAD

**Issue by Dishebh** [CodeTrophs/Backend#126]
### Current Scenario

A user with `userId` can report a `Discussion` with `discussionId` multiple numbers of times. However, this should not be the case.

### Expected Scenario

Before creating a new document in the `ReportDiscussionDetails` model, check if a document, having the same `userId` and `discussionId` already exists. If this is the case, return `Discussion already reported`; else create a new document in the `ReportDiscussionDetails` model.

**Comment by Ninjavin** [comment]
@Dishebh Can you assign this to me? Sorry bit late to the party.

**Comment by Dishebh** [comment]
Sure.

**Comment by Dishebh** [comment]
@Ninjavin, any progress on the issue?
