### ISSUE TITLE
restrict a user to report a particular DiscussionComment only one time 

### ISSUE THREAD

**Issue by Dishebh** [CodeTrophs/Backend#127]
### Current Scenario

A user with `userId` can report a `DiscussionComment` with `commentId` multiple numbers of times. However, this should not be the case.

### Expected Scenario

Before creating a new document in the `ReportDiscussionCommentDetails` model, check if a document, having the same `userId` and `commentId` already exists. If this is the case, return `Comment already reported`; else create a new document in the `ReportDiscussionCommentDetails` model.

**Comment by ankitvashisht12** [comment]
Hey @Dishebh can you please assign this to me ?

**Comment by Dishebh** [comment]
Sure
