### ISSUE TITLE
create a ReportDiscussion model using mongoose schema

### ISSUE THREAD

**Issue by Dishebh** [CodeTrophs/Backend#128]
### Enhancement

Create a `ReportDiscussion` model with documents having keys as:
- `discussionId` as a ref to `Discussion` model to identify and store the `Discussion` that was reported.
- `numberOfReports` as a `Number` which gives the value of the total number of reports the discussion with `discussionId` has received.
- `timestamps` set to true

**Comment by ankitvashisht12** [comment]
Hi @Dishebh 

Isn't this model has already been created in the `src/model/ReportDiscussion.js` file ?

**Comment by Dishebh** [comment]
It is `ReportDiscussionDetails.js`

**Comment by ankitvashisht12** [comment]
Ohh sorry !! it looks like i forked the older version of github repo
