### ISSUE TITLE
Valid ClientId Option Required

### ISSUE THREAD

**Issue by pappyJ** [CodeTrophs/Backend#150]
I clonned the repo to start hacking but i was interrupted by an TypError : TypeError: OAuth2Strategy requires a clientID option

attached is the image of my terminal .. help needed to enable me contribute
![Screenshot from 2021-01-06 16-27-10](https://user-images.githubusercontent.com/65920240/103786348-a0257000-503c-11eb-869a-e4beaf0fa926.png)

**Comment by irshadjsr21** [comment]
Please check the `wiki` for the setup guidelines.

**Comment by pappyJ** [comment]
fixed .. Thanks!!!
