### ISSUE TITLE
Use Response Constants Instead of hard coded values

### ISSUE THREAD

**Issue by pappyJ** [CodeTrophs/Backend#151]

**Comment by Itsaadarsh** [comment]
Hello there @pappyJ , can you please elaborate on this issue so that I can understand it and get started on fixing it. Kindly provide some screenshots too for a better understanding of this issue.

**Comment by pappyJ** [comment]
I already made a PR that was rejected by a maintainer ...

**Comment by pappyJ** [comment]
https://github.com/pappyJ/Backend. Examples here

**Comment by Dishebh** [comment]
Closing the issue as resolved. Please feel free to open up a new issue if anything is missed or something new comes up.
