### ISSUE TITLE
remove the correctIndex field if user not an admin

### ISSUE THREAD

**Issue by Dishebh** [CodeTrophs/Backend#158]
### Current case -
The route GET `/v1/skilltest/:testId` lists all the skill test questions of a particular `testId` with the response object having `correctIndex` as one of the keys (here, the `correctIndex` tells the correct answer for a particular skill test question).

### Expected case - 
The route GET `/v1/skilltest/:testId` should only give back `correctIndex` if and only if the logged-in user is an admin. Else, the `correctIndex` key should not be sent back as a response.

**Comment by ankitvashisht12** [comment]
working on this
