### ISSUE TITLE
Sending email using nodemailer and sendgrid whenever a new user signs up.

### ISSUE THREAD

**Issue by udaymittal7** [CodeTrophs/Backend#170]
Adding an email.js file in utils and adding the email function in user create function in controller to send a welcome email to a new user.

**Comment by Dishebh** [comment]
Great, go ahead.

**Comment by udaymittal7** [comment]
Should I use gmail or sendgrid as the service?

**Comment by aryasoni98** [comment]
@udaymittal7 use gmail .

**Comment by udaymittal7** [comment]
The signup is only using github right? So, should I just add the email function in auth.js file in the githubAuth function?

**Comment by udaymittal7** [comment]
@aryasoni98 @Dishebh ?

**Comment by Dishebh** [comment]
Sure, you can try that.

**Comment by aryasoni98** [comment]
@udaymittal7 Any Update ?

**Comment by srrathi** [comment]
can we use any marketing platform for CRM as well as for all types of emails. There are many companies which provide a lot of services in just their free tier we can try them like I know about one company SendInBlue. We can use them for event tracking as well as email sending. If so can you please assign this issue to me as I've required experience.

**Comment by srrathi** [comment]
Is this issue is closed or resolved?
